# Generated by Django 4.1.7 on 2023-07-24 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('title', models.CharField(help_text='e.g. Data Analyst, Graphic Designer, Photographer...', max_length=500, null=True, verbose_name='Title')),
                ('bio', models.TextField(blank=True, help_text='300 character limit', null=True, verbose_name='Biography')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=users.models.Profile.path_and_rename, verbose_name='Profile Picture')),
                ('linkedin', models.URLField(blank=True, help_text='e.g. "https://www.linkedin.com/in/teachonlearning/"', null=True, verbose_name='LinkedIn')),
                ('instagram', models.URLField(blank=True, help_text='e.g. "https://instagram.com/teachonlearning/"', null=True, verbose_name='Instagram')),
                ('twitter', models.URLField(blank=True, help_text='e.g. "https://twitter.com/teachonlearning/"', null=True, verbose_name='Twitter')),
                ('facebook', models.URLField(blank=True, help_text='e.g. "https://facebook.com/teachonlearning/"', null=True, verbose_name='Facebook')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'users_profiles',
            },
        ),
    ]
