# Generated by Django 4.1.7 on 2023-07-07 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(help_text='e.g. Data Analyst, Graphic Designer, Photographer...', max_length=500, null=True, verbose_name='Title'),
        ),
    ]
