# Generated by Django 4.1.7 on 2023-07-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='website',
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook',
            field=models.URLField(blank=True, help_text='e.g. "https://facebook.com/teachonlearning/"', null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram',
            field=models.URLField(blank=True, help_text='e.g. "https://instagram.com/teachonlearning/"', null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(blank=True, help_text='e.g. "https://www.linkedin.com/in/teachonlearning/"', null=True, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.URLField(blank=True, help_text='e.g. "https://twitter.com/teachonlearning/"', null=True, verbose_name='Twitter'),
        ),
    ]
