# Generated by Django 4.1.7 on 2023-07-09 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_courses_location_map'),
        ('contact', '0002_message_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('first_name', models.CharField(max_length=150, null=True, verbose_name='First name')),
                ('last_name', models.CharField(max_length=150, null=True, verbose_name='Last name')),
                ('email', models.EmailField(max_length=200, null=True, verbose_name='Your email')),
                ('set_schedule', models.CharField(choices=[('Samedi - 9h - 17h', 'Samedi - 9h - 17h'), ('Dimanche - 9h - 17h', 'Dimanche - 9h - 17h'), ('Samedi - 9h - 12h et Dimanche - 9h - 12h', 'Samedi - 9h - 12h et Dimanche - 9h - 12h')], default='+ 10,500 HTG', max_length=150, verbose_name='Quelle horaire vous serait confortable?')),
                ('q_laptop', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=150, verbose_name='Avez-vous un laptop?')),
                ('q_wish', models.CharField(choices=[('En ligne', 'En ligne'), ('En presentiel', 'En presentiel')], default='5,500 - 10,500 HTG', max_length=150, verbose_name='Comment souhaiteriez-vous participer a ce cours?')),
                ('q_hearing_us', models.CharField(choices=[('Site Web', 'Site Web'), ('Amis', 'Amis'), ('Email', 'Email'), ('Whatsapp', 'Whatsapp'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('Television', 'Television')], default='4,000 - 5,500 HTG', max_length=150, verbose_name='Comment avez-vous entendu parler de cet événement?')),
                ('q_certificate', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=150, verbose_name='Souhaiteriez-vous obtenir un certificat?')),
                ('q_price', models.CharField(choices=[('4,000 - 5,500 HTG', '4,000 - 5,500 HTG'), ('5,500 - 10,500 HTG', '5,500 - 10,500 HTG'), ('+ 10,500 HTG', '+ 10,500 HTG')], default='5,500 - 10,500 HTG', max_length=150, verbose_name='Combien esperez vous la participation?')),
                ('message', models.TextField(null=True, verbose_name='Tell us more about you, and how wish us to help you with this course')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_student_course_rel', to='courses.courses', verbose_name='What course you would like to learn?')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
