# Generated by Django 4.1.7 on 2023-07-06 00:45

import courses.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Slug')),
                ('code', models.CharField(help_text='Max 10 characters', max_length=15, null=True, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, help_text='Write in some lines more info about this category', null=True, verbose_name='Description')),
                ('seo_keywords', models.CharField(blank=True, help_text="Add keyword using a comma (e.g. 'politics,business,finance')", max_length=300, null=True, verbose_name='Keywords')),
                ('seo_description', models.TextField(blank=True, help_text='300 character limit', max_length=350, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('last_edit', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated On')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'courses_category',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('last_edit', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated On')),
            ],
            options={
                'verbose_name': 'Tags',
                'verbose_name_plural': 'Tags',
                'db_table': 'courses_tags',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('name', models.CharField(max_length=300, null=True, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Write in some lines more info about this course', null=True, verbose_name='Description')),
                ('price', models.FloatField(blank=True, help_text='Price in HTG', null=True, verbose_name='Price')),
                ('start_date', models.DateField(null=True, verbose_name='Start date')),
                ('end_date', models.DateField(null=True, verbose_name='End date')),
                ('cover', models.ImageField(default=None, null=True, upload_to=courses.models.Courses.path_and_rename, verbose_name='Cover')),
                ('set_certificate', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=150, verbose_name='Certificate')),
                ('set_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Professional', 'Professional')], default='Beginner', max_length=150, verbose_name='Skill level')),
                ('set_language', models.CharField(choices=[('French', 'French'), ('English', 'English'), ('Haitian creole', 'Haitian creole')], default='Haitian creole', max_length=150, verbose_name='Language')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Draft', max_length=100, verbose_name='Status')),
                ('seo_keywords', models.CharField(blank=True, help_text="Add keyword using a comma (e.g. 'politics,business,finance')", max_length=300, null=True, verbose_name='Keywords')),
                ('seo_description', models.TextField(blank=True, help_text='300 character limit', max_length=350, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('last_edit', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated On')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_category_rel', to='courses.category', verbose_name='Category')),
                ('tags', models.ManyToManyField(blank=True, help_text='Add some tags', related_name='courses_tags_rel', to='courses.tags', verbose_name='Tags')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_teacher_rel', to='users.profile', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses_cs',
            },
        ),
    ]
