# Generated by Django 4.1.7 on 2023-07-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='location',
            field=models.CharField(max_length=200, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='location_map',
            field=models.TextField(help_text='Insert the google map iFrame code', null=True, verbose_name='Location map'),
        ),
    ]
