# Generated by Django 4.1.7 on 2023-07-06 23:38

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='introduction',
            field=models.TextField(blank=True, help_text='Write in some lines more info about this course', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=tinymce.models.HTMLField(help_text='Start writing about this course...', null=True, verbose_name='Description'),
        ),
    ]
