# Generated by Django 4.1.7 on 2023-07-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courses_introduction_alter_courses_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='introduction',
            field=models.TextField(blank=True, help_text='Write in some lines more info about this course', null=True, verbose_name='Introduction'),
        ),
    ]
