# Generated by Django 4.1.7 on 2023-07-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_category_name_alter_courses_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='location_map',
            field=models.TextField(blank=True, help_text='Insert the google map iFrame code', null=True, verbose_name='Location map'),
        ),
    ]
