# Generated by Django 4.1.7 on 2023-07-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='price',
            field=models.IntegerField(blank=True, help_text='Price in HTG', null=True, verbose_name='Price'),
        ),
    ]
