# Generated by Django 4.1.7 on 2023-07-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_courses_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='location',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Location'),
        ),
    ]
