# Generated by Django 4.1.7 on 2023-07-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_courses_location_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='location_map',
            field=models.TextField(help_text='Insert the google map iFrame code', null=True, unique=True, verbose_name='Location map'),
        ),
    ]
