# Generated by Django 4.1.7 on 2023-07-09 16:26

import company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, unique=True, verbose_name='Name')),
                ('message', models.TextField(null=True, verbose_name='Message')),
                ('title', models.CharField(max_length=200, null=True, unique=True, verbose_name='Title')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=company.models.Testimonials.path_to_avatar, verbose_name='Profil Picture')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_edit', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated On')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
